
import Image from 'next/image';
import Tata from '../../public/assets/Truck logos/tata.png'
import ashok from '../../public/assets/Truck logos/ashok.png'
import asian from '../../public/assets/Truck logos/asian.png'
import bajaj from '../../public/assets/Truck logos/bajaj.jpg'
import bharath from '../../public/assets/Truck logos/bharathbenz.png'
import eicher from '../../public/assets/Truck logos/eicher.gif'
import force from '../../public/assets/Truck logos/force.png'
import isuzu from '../../public/assets/Truck logos/isuzu.jpg'
import mahindra from '../../public/assets/Truck logos/mahindra.jpg'
import marthi from '../../public/assets/Truck logos/ms.png'
import piago from '../../public/assets/Truck logos/Piaggio.png'
import Volvo from '../../public/assets/Truck logos/Volvo.jpg'


export  const  truckBrands = [
    { name: "Tata Motors", image: <Image src={Tata} alt='tata' width="60px" height="50px" className='' />},
    { name: "Ashok Leyland", image:<Image src={ashok} alt='ashok'  width="60px" height="50px"/>},
    { name: "asian", image: <Image src={asian} alt='asian'  width="60px" height="50px"/>},
    { name: "bajaj", image:<Image src={bajaj} alt='bajaj'  width="60px" height="50px"/>},
    { name: "bharath", image: <Image src={bharath} alt='bharath'  width="60px" height="50px"/>},  
    { name: "eicher", image: <Image src={eicher} alt='eicher'  width="60px" height="50px"/>},
    { name: "force", image: <Image src={force} alt='force'  width="60px" height="50px"/>},
    { name: "isuzu", image: <Image src={isuzu} alt='isuzu'  width="60px" height="50px"/>},
    { name: "mahindra", image: <Image src={mahindra} alt='mahindra'  width="60px" height="50px"/>},
    { name: "marthi", image:<Image src={marthi} alt='ms'  width="60px" height="50px" />},
    { name: "piago", image: <Image src={piago} alt='piago'  width="60px" height="50px"/>},
    { name: "Volvo", image: <Image src={Volvo} alt='Volvo'  width="60px" height="50px"/>},
  ];
  
  export const fuel=[
    "Petrol",
    "Disel",
    "Gas",
    "LPG",
    "CNG"
]
 
export const planning=[
    "Within this week",
    "By next week",
    "After 2 weeks",
    "Just checking price"
  ]
  export const truckBody = [
    "Truck",
    "Pickup",
    "Mini Truck",
    "Tipper",
    "Trailer",
    "3 Wheeler",
    "Transit Mixer",
    "Auto Rickshaw",
    "E Rickshaw"
  ];
  export const  vehicleLocation = [
    "Agra",
    "Ahmednagar",
    "Ajmer",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Allahabad",
    "Alwar",
    "Ambala",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Anand",
    "Asansol",
    "Aurangabad",
    "Azamgarh",
    "Balasore",
    "Ballia",
    "Banda",
    "Barabanki",
    "Baramati",
    "Bareilly",
    "Basti",
    "Bathinda",
    "Beed",
    "Belgaum",
    "Berhampur",
    "Bhagalpur",
    "Bharatpur",
    "Bharuch",
    "Bhavnagar",
    "Bhilai",
    "Bhilwara",
    "Bhiwani",
    "Bhopal",
    "Bhubaneswar",
    "Bijapur",
    "Bikaner",
    "Bilaspur",
    "Bokaro",
    "Bulandshahar",
    "Buldana",
    "Burhanpur",
    "Calicut",
    "Chalakudy",
    "Chandigarh",
    "Chandrapur",
    "Chhindwara",
    "Chitradurga",
    "Coimbatore",
    "Cuddalore",
    "Cuttack",
    "Dahod",
    "Darbhanga",
    "Davangere",
    "Deesa",
    "Dehradun",
    "Dewas",
    "Dhanbad",
    "Dharwad",
    "Dhule",
    "Dibrugarh",
    "Dindigul",
    "Durgapur",
    "Etawah",
    "Faizabad",
    "Faridabad",
    "Firozabad",
    "Gandhidham",
    "Gandhinagar",
    "Gaya",
    "Goa",
    "Godhra",
    "Gondal",
    "Gorakhpur",
    "Guntur",
    "Guruvayur",
    "Guwahati",
    "Gwalior",
    "Hajipur",
    "Haldwani",
    "Hanumangarh",
    "Hapur",
    "Hardoi",
    "Haridwar",
    "Hassan",
    "Hathras",
    "Himatnagar",
    "Hisar",
    "Hooghly",
    "Hoshiarpur",
    "Hosur",
    "Howrah",
    "Hubli",
    "Jabalpur",
    "Jalandhar",
    "Jalgaon",
    "Jalna",
    "Jamnagar",
    "Jamshedpur",
    "Jaunpur",
    "Jhajjar",
    "Jhansi",
    "Jhunjhunu",
    "Jind",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Kakinada",
    "Kalol",
    "Kannur",
    "Kanpur",
    "Karad",
    "Karimnagar",
    "Karnal",
    "Kasaragod",
    "Kashipur",
    "Katni",
    "Kayamkulam",
    "Kolhapur",
    "Kollam",
    "Korba",
    "Kota",
    "Kottayam",
    "Kurukshetra",
    "Latur",
    "Ludhiana",
    "Madurai",
    "Malappuram",
    "Malda",
    "Mandya",
    "Mangalore",
    "Mathura",
    "Meerut",
    "Mehsana",
    "Mohali",
    "Moradabad",
    "Muvattupuzha",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysore",
    "Nadiad",
    "Nagercoil",
    "Nagpur",
    "Namakkal",
    "Nanded",
    "Nashik",
    "Navsari",
    "Nellore",
    "North 24 Parganas",
    "Palakkad",
    "Palanpur",
    "Pali",
    "Palwal",
    "Panchkula",
    "Panchmahal",
    "Panipat",
    "Parassala",
    "Patan",
    "Pathanamthitta",
    "Pathankot",
    "Patiala",
    "Patna",
    "Pilibhit",
    "Pollachi",
    "Pondicherry",
    "Puri",
    "Raipur",
    "Rajahmundry",
    "Rajkot",
    "Rajnandgaon",
    "Rampur",
    "Ranchi",
    "Ranipet",
    "Ratlam",
    "Rewa",
    "Rewari",
    "Rohtak",
    "Rourkela",
    "Rudrapur",
    "Sagar",
    "Saharanpur",
    "Salem",
    "Samastipur",
    "Sambalpur",
    "Sangli",
    "Satara",
    "Satna",
    "Shahjahanpur",
    "Shimoga",
    "Shrirampur",
    "Sikar",
    "Siliguri",
    "Singrauli",
    "Sitapur",
    "Solapur",
    "Sonipat",
    "Sriganganagar",
    "Surat",
    "Surendranagar",
    "Thanjavur",
    "Thodupuzha",
    "Thrissur",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupati",
    "Tiruppur",
    "Tirur",
    "Trivandrum",
    "Tumkur",
    "Udaipur",
    "Udupi",
    "Ujjain",
    "Unnao",
    "Vadakara",
    "Vadodara",
    "Valsad",
    "Vapi",
    "Varanasi",
    "Vijayawada",
    "Visakhapatnam",
    "Warangal",
    "Wardha",
    "Yavatmal",
    "Zirakpur"
  ];
  
  export const popularCities=[
    "New Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Gurgaon",
    "Chennai",
    "Pune",
    "Noida",
    "Ghaziabad",
    "Lucknow",
    "Jaipur",
    "Kolkata",
    "Kochi",
    "Indore"
  ]
  
  export const registrationStateAndCode = [
    {
      id:1,
      name: "Delhi",
      code: "DL-",
      number: [
        "DL04",
        "DL05",
        "DL03",
        "DL01",
        "DL06",
        "DL07",
        "DL08",
        "DL02",
        "DL09",
        "DL10",
        "DL11",
        "DL13",
        "DL12",
        "DL14",
      ],
    },
    {  id:2,
      name: "Kerala",
      code: "KL-",
      number: [
        "KL04",
        "KL66",
        "KL64",
        "KL30",
        "KL79",
        "KL07",
        "KL39",
        "KL43",
        "KL46",
        "KL68",
        "KL69",
        "KL06",
        "KL37",
        "KL34",
        "KL13",
        "KL82",
        "KL23",
        "KL84",
        "KL14",
        "KL85",
        "KL29",
        "KL74",
        "KL47",
        "KL02",
        "KL61",
        "KL77",
        "KL44",
        "KL67",
        "KL24",
        "KL35",
        "KL81",
        "KL05",
        "KL11",
        "KL56",
        "KL57",
        "KL65",
        "KL80",
        "KL28",
        "KL10",
        "KL50",
        "KL17",
        "KL21",
        "KL20",
        "KL49",
        "KL70",
        "KL51",
        "KL09",
        "KL42",
        "KL19",
        "KL76",
        "KL03",
        "KL83",
        "KL78",
        "KL53",
        "KL54",
        "KL73",
        "KL58",
        "KL01",
        "KL15",
        "KL22",
        "KL08",
        "KL55",
        "KL36",
        "KL75",
        "KL12",
        "KL72",
        "KL41",
        "KL26",
        "KL63",
        "KL16",
        "KL33",
        "KL32",
        "KL45",
        "KL60",
        "KL71",
        "KL31",
        "KL52",
        "KL40",
        "KL62",
        "KL25",
        "KL27",
        "KL38",
        "KL59",
        "KL18",
        "KL48",
      ],
    },
    {
      id:3,
      name: "Maharashtra",
      code: "MH-",
      number: [
        "MH16",
        "MH30",
        "MH44",
        "MH27",
        "MH20",
        "MH28",
        "MH34",
        "MH18",
        "MH33",
        "MH35",
        "MH38",
        "MH19",
        "MH09",
        "MH24",
        "MH47",
        "MH02",
        "MH03",
        "MH01",
        "MH31",
        "MH40",
        "MH26",
        "MH15",
        "MH51",
        "MH43",
        "MH06",
        "MH14",
        "MH12",
        "MH53",
        "MH54",
        "MH55",
        "MH08",
        "MH10",
        "MH11",
        "MH07",
        "MH13",
        "MH04",
        "MH32",
        "MH29",
        "MH45",
        "MH42",
        "MH23",
        "MH36",
        "MH49",
        "MH21",
        "MH50",
        "MH05",
        "MH41",
        "MH39",
        "MH46",
        "MH22",
        "MH52",
        "MH25",
        "MH17",
        "MH48",
        "MH37",
      ],
    },
    {
      id:4,
      name: "Uttar Pradesh",
      code: "UP-",
      number: [
        "UP81",
        "UP70",
        "UP80",
        "UP45",
        "UP23",
        "UP79",
        "UP28",
        "UP50",
        "UP40",
        "UP17",
        "UP47",
        "UP41",
        "UP51",
        "UP66",
        "UP20",
        "UP67",
        "UP96",
        "UP52",
        "UP25",
        "UP82",
        "UP75",
        "UP42",
        "UP71",
        "UP83",
        "UP76",
        "UP14",
        "UP61",
        "UP53",
        "UP18",
        "UP91",
        "UP30",
        "UP37",
        "UP92",
        "UP93",
        "UP77",
        "UP78",
        "UP74",
        "UP87",
        "UP73",
        "UP31",
        "UP94",
        "UP36",
        "UP32",
        "UP56",
        "UP54",
        "UP85",
        "UP15",
        "UP63",
        "UP21",
        "UP12",
        "UP16",
        "UP57",
        "UP26",
        "UP72",
        "UP33",
        "UP11",
        "UP38",
        "UP58",
        "UP27",
        "UP19",
        "UP46",
        "UP55",
        "UP34",
        "UP64",
        "UP04",
        "UP65",
        "UP90",
        "UP60",
        "UP24",
        "UP13",
        "UP43",
        "UP86",
        "UP62",
        "UP95",
        "UP84",
        "UP22",
        "UP44",
        "UP35",
      ],
    },
    {
      id:5,
      name: "West Bengal",
      code: "WB-",
      number: [
        "WB19",
        "WB22",
        "WB69",
        "WB70",
        "WB37",
        "WB44",
        "WB38",
        "WB61",
        "WB62",
        "WB28",
        "WB25",
        "WB26",
        "WB42",
        "WB43",
        "WB41",
        "WB95",
        "WB45",
        "WB54",
        "WB53",
        "WB88",
        "WB47",
        "WB48",
        "WB63",
        "WB64",
        "WB86",
        "WB85",
        "WB76",
        "WB77",
        "WB97",
        "WB98",
        "WB39",
        "WB40",
        "WB16",
        "WB15",
        "WB17",
        "WB18",
        "WB11",
        "WB13",
        "WB12",
        "WB14",
        "WB92",
        "WB91",
        "WB71",
        "WB72",
        "WB59",
        "WB60",
        "WB75",
        "WB04",
        "WB06",
        "WB07",
        "WB02",
        "WB08",
        "WB09",
        "WB03",
        "WB05",
        "WB10",
        "WB01",
        "WB66",
        "WB83",
        "WB65",
        "WB84",
        "WB58",
        "WB94",
        "WB93",
        "WB57",
        "WB52",
        "WB89",
        "WB90",
        "WB51",
        "WB27",
        "WB33",
        "WB36",
        "WB50",
        "WB34",
        "WB55",
        "WB56",
        "WB81",
        "WB82",
        "WB46",
        "WB73",
        "WB74",
        "WB20",
        "WB96",
        "WB30",
        "WB29",
        "WB68",
        "WB23",
        "WB24",
        "WB67",
        "WB31",
        "WB32",
        "WB79",
        "WB78",
      ],
    },
    {
      id:6,
      name: "Andhra Pradesh",
      code: "AP-",
      number: [
        "AP02",
        "AP33",
        "AP08",
        "AP07",
        "AP09",
        "AP12",
        "AP11",
        "AP13",
        "AP04",
        "AP14",
        "AP15",
        "AP20",
        "AP21",
        "AP22",
        "AP24",
        "AP26",
        "AP25",
        "AP39",
        "AP05",
        "AP28",
        "AP29",
        "AP23",
        "AP10",
        "AP30",
        "AP03",
        "AP17",
        "AP18",
        "AP19",
        "AP31",
        "AP32",
        "AP35",
        "AP16",
        "AP34",
        "AP36",
        "AP37",
        "AP38",
        "AP06",
        "AP01",
        "AP27",
      ],
    },
  ];
  
  export const mileageRanges=[
    "0 - 10,000 Km",
    "10,000 - 20,000 Km",
    "20,000 - 30,000 Km",
    "30,000 - 40,000 Km",
    "40,000 - 50,000 Km",
    "50,000 - 60,000 Km",
    "60,000 - 70,000 Km",
    "70,000 - 80,000 Km",
    "80,000 - 90,000 Km",
    "90,000 - 1,00,000 Km",
    "Above 1,00,000 km",
  ];


  export const vehicleCondition=["Brand New","Excellent Conditon","Gently Used","Fair Conditon","Rougly Used"]